/*10번 부서 소속사원들 중 직급이 과장인 사원의 이름, 부서번호, 직급조회*/

SELECT ENAME,DNO,JOB
FROM EMPLOYEE
WHERE JOB='과장' AND DNO = 10

/*10번 부서 소속된 사원이거나 직급이 과장인 사원의 이름, 부서번호, 직급조회*/

SELECT ENAME,DNO,JOB
FROM EMPLOYEE
WHERE JOB='과장' OR DNO = 10

/*10번 부서에 소속된 사원을 제외한 사원의 이름, 부서번호, 직급조회*/

SELECT ENAME,DNO,JOB
FROM EMPLOYEE
WHERE NOT DNO = 10

/*급여가 400이상 500이하인 사원 모든 정보 출력*/

SELECT *
FROM EMPLOYEE
WHERE SALARY>=400 AND SALARY <=500

/*급여가 400미만이거나 500초과인 사원 모든 정보 출력*/

SELECT *
FROM EMPLOYEE
WHERE SALARY < 400 OR SALARY > 500

/*커미션이 80이거나 100이거나 200인 사원의 모든 정보 출력*/

SELECT *
FROM EMPLOYEE
WHERE COMMISSION = 80 OR COMMISSION  = 100 OR COMMISSION = 200

SELECT*
FROM EMPLOYEE
WHERE COMMISSION IN (80,100,200)

/*커미션이 80,100,200이 아닌 사원의 모든 정보 출력*/

SELECT *
FROM EMPLOYEE
WHERE NOT COMMISSION = 80 AND NOT COMMISSION = 100 AND NOT COMMISSION = 200

SELECT *
FROM EMPLOYEE
WHERE NOT(COMMISSION =80 OR COMMISSION = 100 OR COMMISSION = 200)

SELECT *
FROM EMPLOYEE
WHERE COMMISSION NOT IN(80,100,200)
