/*급여가 300 이하인 사원의 사원번호, 이름, 급여 출력*/

SELECT ENO,ENAME,SALARY
FROM EMPLOYEE
WHERE SALARY < 300

/*사원 이름이 "오지호"인 사원의 사원번호, 이름, 급여 출력*/

SELECT ENO, ENAME, SALARY
FROM EMPLOYEE
WHERE ENAME = '오지호'

/*급여가 250 이거나 300이거나 500인 사원의 이름과 급여 출력(논리 연산자 사용)*/

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY =250 OR SALARY = 300 OR SALARY = 500

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY IN (250,300,500)


/*급여가 250이거나 300이거나 500이 아닌 사원의 사원번호, 이름, 급여 출력*/

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE NOT (SALARY =250 OR SALARY = 300 OR SALARY = 500)

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY NOT IN (250,300,500)

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY != 250 AND SALARY != 300 AND SALARY != 500

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE NOT SALARY = 250 AND NOT SALARY = 300 AND NOT SALARY =500


